lib/charms/grafana_agent_k8s/v0/grafana_agent.py
metadata.yaml
src/charm.py

This PR implements the grafana agent library.
This document explains how to integrate a workload charm that needs to send logs to a
`Loki` or a `Grafana agent` charm that implements the `loki_push_api` interface.
The underlying idea is that this library will create and manage a side-car container
in the pod of the workload charm that will run `Promtail` as a `LogProxy` to forward logs
through `loki_push_api` interface.
1.  Use the `LogProxyConsumer` object in a workload charm as shown in the library docstrings
2. Pack the `grafana-agente-operator` and the workload charm.
3. Add a custom juju model: `$ juju add-model logproxy`
4. Deploy both charms:
- Grafana agent: `$ juju deploy ./grafana-agent-k8s_ubuntu-20.04-amd64.charm --resource agent-image=grafana/agent:v0.19.0` 
- Workload:  `$ …

WIP: Grafana agent lib. First functional approach

---

CONTRIBUTING.md
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/charm.py

Previously, the `_loki_config()` method in the charm checked the type of the object passed in. If it was an event from the consumer that the relation was joined (which really means "has a consumer"), a Loki config was generated. If it was broken, it was removed.
However, the "default" case also generated an empty config, and the same object was blindly passed around without typechecking. A type assertion would easily have missed a `PebbleReadyEvent`, `None`, a `Relation*` event, or anything else which made it there, and generated an empty Loki config the first time anything happened to the charm which was _not_ a change to the logging relation.
Type check *before* we try to generate the Loki config stub.
Also, update the docs for which image is needed to make an easy deployment example. …

Fix the logic around generating Loki configuration

---

src/charm.py

This PR fixes #34.
There are 2 way to test this PR:
- Deploy Loki and deploy 2 Grafana agents
- Relate both charms
- Check the grafana agent config file has the `loki` section
- **Stop the multipass VM** in which Juju and microk8s are running.
- Start the multipass VM again.
- Check that once microk8s is up and running again the grafana agent config has the `loki` section
- Deploy Loki and deploy 2 Grafana agents
- Relate both charms
- Check the grafana agent config file has the `loki` section
- **Delete** the grafana agent pod with: `microk8s.kubectl delete pods grafana-agent-k8s-0 -n observability`
- Wait until the pod is deleted and Juju creates a new unit to replace the deleted one.
- Check grafana agent config has the `loki` section

Loki config missing if VM running juju and microk8s is restarted or pod is deleted

---

CONTRIBUTING.md
README.md

The indicated version of the used **grafana-agent** is outdated compared to the one used in the latest revision.
Updating the files where `v0.20.1` appears, correcting it to `v0.26.1`.
Updating the **grafana-agent** version in the documentation to the version used in the latest revision.

Fix grafana-agent version in docs

---

metadata.yaml

To prevent people from mistakenly trying to deploy this charm on lxd or similar, add an assumption about the k8s-api being available.

assume k8s api is available

---

src/grafana_agent.py
src/k8s_charm.py
src/machine_charm.py
tests/unit/test_alerts.py
tests/unit/test_scrape_configuration.py

Make the codebase less muddy.
Move machine agent stuff (`*_primary`) out of the main class, sync up config locations/generation so it's not a series of appended dicts from different places. 
Create methods to be overridden for per-machine/k8s config block additions (this also makes the `is_machine` method unnecessary), which are appended as part of the "wholesale" config generation in the main class body.
Fix the unit tests.

Class split

---

config.yaml
src/grafana_agent.py
src/machine_charm.py
tests/unit/test_scrape_configuration.py

Add a config option for insecure skip verify of TLS, so that self-signed certificates can be used.
The `insecure_skip_verify` option is taken as a configuration parameter and passed when assembling the configuration, specifically to:
* [remote writes](https://grafana.com/docs/agent/latest/configuration/metrics-config/#metrics_instance_config)
* [integrations prometheus_remote_writes](https://grafana.com/docs/agent/latest/configuration/integrations/)
* [loki client endpoints](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients)
[OPENG-1232]: https://warthogs.atlassian.net/browse/OPENG-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add option for tls insecure skip verify

---

.github/workflows/release-edge.yaml
k8s_metadata.yaml
machine_metadata.yaml
src/grafana_agent.py
src/grafana_dashboards/grafana-agent-node-exporter-quickstart_rev2.json
src/grafana_dashboards/node-exporter-full.json
src/k8s_charm.py
src/machine_charm.py
tests/scenario/machine_charm/test_dashboards.py
tox.ini

The charm doesn't have a `grafana_dashboards` relation for forwarding dashboards.
We need to be able to forward dashboards:
- Machine charm: over `cos_machine` relation
- K8s charm: over `grafana_dashboards` (requirer) relation
```mermaid
graph LR
kafka --cos_machine--- agent_machine["agent (machine)"] --"grafana_dashboards"--- grafana-k8s
some-app --grafana_dashboards--- agent_k8s["agent (k8s)"] --grafana_dashboards--- grafana-k8s
subgraph gagent_charmdir["Grafana agent charm dir"]
agent_machine
gadashboards[(Built-in dashboards)]
agent_k8s
end
subgraph kafka_charmdir["kafka charm dir"]
kafka
kdashboards[(Built-in dashboards)]
end
subgraph some_app_charmdir["some charm dir"]
some-app
sdashboards[(Built-in dashboards)]
end
```
Fixes #87.
Add relation handlers for grafana dashboards.

Add dashboards handler

---

machine_metadata.yaml
src/grafana_agent.py
src/k8s_charm.py
src/machine_charm.py

Afaiu, in order to remove the two relations in machine's metadata that `cos_machine` is intended to replace, we would need to further separate between the machine and k8s codes.
Remove from machine metadata:
- prometheus_scrape requirer
- loki_push_api provider

Clear machine metadata relations

---

INTEGRATING.md
lib/charms/grafana_agent/v0/cos_agent.py
machine_metadata.yaml
src/grafana_agent.py
src/machine_charm.py
tests/integration/loki-tester/README.md
tests/integration/loki-tester/src/charm.py
tests/scenario/test_machine_charm/test_scrape_configs.py
tests/unit/k8s/test_scrape_configuration.py
tests/unit/machine/test_update_status.py

Lib/iface name has "machine" in it, which is redundant.
Rename to `cos-agent`.

Rename cos-machine to cos-agent

---

k8s_metadata.yaml

Now that we actually tag it, put it back in the metadata so we never forget (this PR is to ensure CI still goes green, basically)

Try the latest ROCK tag again

---

lib/charms/grafana_agent/v0/cos_agent.py
src/grafana_agent.py

This PR fixes #135 
This PR fixes:
- The dashboard's malformed files names
- Dashboards content: There is no need to transform the content of the dashboard, since the [lib returns a string](https://github.com/canonical/grafana-agent-k8s-operator/blob/machine_charm/lib/charms/grafana_agent/v0/cos_agent.py#L475)
- Files overwrite: As we generated the same name, the files were overwritten.

FIX Grafana dashboards files are stored in a bad format

---

lib/charms/grafana_agent/v0/cos_agent.py

Closes #140.
Move the config information to the unit databag instead of the application one.
Pack this charm, add this library to the Kafka charm and pack it; scale up Kafka and then set up the `cos-agent` relation, then relating the agent to Prometheus. Verify that metrics for all units are in Prometheus.

move on-refresh config to unit databag

---

lib/charms/grafana_agent/v0/cos_agent.py
src/grafana_agent.py
src/k8s_charm.py
src/machine_charm.py
tests/unit/k8s/test_relation_status.py
tests/unit/machine/test_relation_status.py
tox.ini

A WaitingStatus was set only for a scrape - remote-write pair (k8s).
We need to inform the admin of missing relation for all pairs, for both k8s and machine relations.
Iterate over all (incoming, outgoing) relation pairs and set to Blocked if an outgoing relation is missing.
Fixes #104.
NTA.
- Establish "incoming" relations without and "outgoing" pair.
- Incrementally add an "outgoing" relation and see how the status changes.
Set BlockedStatus per relation.

Set BlockedStatus per relation

---

src/k8s_charm.py
tests/unit/k8s/test_alerts.py

More unit tests in yet another repo using uuids which jujutopology won't validate. Replace them with "actual" uuids.
Replace `_scrape.alerts()` with `_scrape.alerts` now that our libraries don't mix and match properties and `Callable`

Use an actual uuid4, alerts() is now a property everywhere

---

lib/charms/operator_libs_linux/v1/snap.py
src/grafana_dashboards/node-exporter-full.json

`node-exporter` dashboard was using `${DS_PROMETHEUS}`.
Replace DS_PROMETHEUS with prometheusds.
Fixes #147.
This shouldn't have been an issue after https://github.com/canonical/grafana-k8s-operator/pull/160. Need to investigate why DS_PROMETHEUS didn't work.
NTA
Replace DS_PROMETHEUS with prometheusds

Replace DS_PROMETHEUS with prometheusds

---

lib/charms/grafana_agent/v0/cos_agent.py

Adds typing annotation for `COSAgentProvider`'s `metrics_endpoints` init arg.
Fixes #106

Typed metrics endpoint dict

---

src/machine_charm.py

Closes #163.
The `__path__` of the log files can be a glob; however, the globbing library will always include both files and directories. `**` alone will include the files (which is the desired behavior), but won't remove the `file is directory` errors.  
Thus, a [drop pipeline](https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/) is added to drop those messages specifically from the data flow.
Deploy according to the issue description and verify those messages don't appear anymore.
Correctly traverse log directories for the machine charm.

fix log directory traversal for machine charm

---

pyproject.toml
src/grafana_agent.py
src/k8s_charm.py
src/machine_charm.py
tests/integration/helpers.py
tests/scenario/test_machine_charm/test_cos_agent_e2e.py
tests/scenario/test_machine_charm/test_scrape_configs.py
tests/scenario/test_start_statuses.py
tests/unit/machine/test_fstab_parsing.py
tox.ini

The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being one new rule being ignored (which wasn't checked before anyway):
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.

use ruff instead of flake8

---

src/machine_charm.py
tests/scenario/test_machine_charm/test_scrape_configs.py

After tackling #163 with #175, the Grafana Agent snap started crashing. Turns out that the specified pipeline stage is causing the issue:
```
Apr 28 10:12:13 juju-5a1d83-0 grafana-agent.grafana-agent[15458]: ts=2023-04-28T10:12:13.077284721Z caller=main.go:64 level=error msg="error creating the agent server entrypoint" err="unable to apply config for log_file_scraper: unable to create logs instance: failed to make file target manager: invalid drop stage config: 1 error(s) decoding:\n\n* 'source' expected type 'string', got unconvertible type '[]interface {}', value: '[level msg]'"
```
Regardless of the pipeline stage [documentation](https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/) specifying it does accept a list of values, the agent doesn't take it.
Remove the `source` …

fix crashes from log glob change

---

src/prometheus_alert_rules/memory.rules
src/prometheus_alert_rules/memory_pressure.rule

- add alert for memory prediction reaching threshold
- add alert for memory reaching threshold
- add alert for swap reaching threshold
Moving memory NRPE checks from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Tested with
```yaml
rule_files:
- memory.rules
tests:
- interval: 1m
input_series:
- series: 'node_memory_MemFree_bytes{instance="test-model_1234_test-app_test-app/0"}'
values: '450 380 250 92 50 31 29 5 5 5 48 150 380 450 450'
- series: 'node_memory_Cached_bytes{instance="test-model_1234_test-app_test-app/0"}'
values: '0x15'
- series: 'node_memory_Buffers_bytes{instance="test-model_1234_test-app_test-app/0"}'
values: '0x15'
- series: 'node_memory_SReclaimable_bytes{instance="test-model_1234_test-app_test-app/0"}'
values: '0x15'
- …
```

Add more alert rules for memory

---

src/prometheus_alert_rules/reboot.rules

- add alert rule for reboot detection
Moving network NRPE checks from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Tested with
```yaml
rule_files:
- reboot.rules
tests:
- interval: 1m
input_series:
- series: 'node_boot_time_seconds{instance="test-model_1234_test-app_test-app/0"}'
values: '100x5 105x2 107x5'  # boot times 100, 105 and 107
alert_rule_test:
- eval_time: 5m
alertname: HostReboot
exp_alerts: []  # no alert
- eval_time: 6m
alertname: HostReboot
exp_alerts:
- exp_labels:
severity: warning
instance: test-model_1234_test-app_test-app/0
exp_annotations:
summary: Host machine rebooted recently (instance test-model_1234_test-app_test-app/0)
description: >-
Host machine rebooted recently.
VALUE = 1
LABELS = …
```

Add alert rules for reboot

---

src/prometheus_alert_rules/disk.rules

- add alert rule for root disk space prediction reaching threshold
- add alert rule for root disk space reaching threshold
- add alert rule for checking readonly moutpoints
- add alert rule for XFS errors
- add alert rule for high read/write disk usage rate
Moving disk NRPE checks from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Tested with
```yaml
rule_files:
- disk.rules
tests:
- interval: 1m
input_series:
- series: 'used_disk_space{instance="test-model_1234_test-app_test-app/0", mountpoint="/"}'
values: '10x60 20x60 30x60 40x60 50x60 60x60 70x60 80x60 90x60 100x60'
promql_expr_test:
- expr: used_disk_space
eval_time: 1h
exp_samples:
- labels: '{__name__="used_disk_space", instance="test-model_1234_test-app_test-app/0", mountpoint="/"}' …
```

Add alert rules for disk utilization

---

src/prometheus_alert_rules/process.rules

Moving OS-level NRPE checks (Processes related) from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Adding reasonable default Prometheus alert rule in Granada agent charm.
These alert rules depends on `collector.processes` which is currently not enabled by default, and is not configurable in this charm (or grafana-agent snap to be more specific). These alert rules won't be effective if issue #162 is not resolved.
Tested with `promtool`
```yaml
rule_files:
- process.rules
tests:
- interval: 1m
input_series:
- series: 'node_processes_max_processes{instance="test-instance-0", job="node"}'
values: 4194304
- series: 'node_processes_pids{instance="test-instance-0", job="node"}'
values: 4
- series: …
```

Add Prometheus alert rule for processes.

---

src/machine_charm.py

https://github.com/canonical/grafana-agent-k8s-operator/pull/197 won't work without the optional `logind` and `systemd` collectors enabled.
Enabling the two collectors above, as well as a couple of additional ones that could prove useful.
Deploy and make sure the `node_systemd_unit_state` metric is properly populated.
Enable additional optional collectors.

enable some additional useful collectors

---

src/prometheus_alert_rules/arp_cache.rules

Add alert for arp cache reaching 80& threshold. This alert rule needs grafana-agent version 0.33.1 and higher, at the same time sysctl collector must be enabled with the following configuration:
```yaml
enable_collectors:
- arp
- sysctl
sysctl_include:
- net.ipv4.neigh.default.gc_thresh3
```
This changes are blocked by [PR](https://github.com/simskij/grafana-agent/pull/17).
Moving memory NRPE checks from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Tested with
```yaml
rule_files:
- arp_cache.rules
tests:
- interval: 1m
input_series:
- series: 'node_arp_entries{instance="test-model_1234_test-app_test-app/0"}'
values: '3 3 3 3 950 950 950 3 3 3'
- series: 'node_sysctl_net_ipv4_neigh_default_gc_thresh3{instance="test-model_1234_test-app_test-a …
```

Add alert rule for arp cache

---

src/prometheus_alert_rules/.wokeignore
src/prometheus_alert_rules/network.rules

- add alert rule for interface MTU size change
- add alert rule for interface speed change
- add alert rule for interface DOWN
- add alert rule for high network receive/transmit errors
- add alert rule for bond degradation
Moving network NRPE checks from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Tested with
```yaml
rule_files:
- network.rules
tests:
- interval: 1m
input_series:
- series: 'node_network_mtu_bytes{instance="test-model_1234_test-app_test-app/0", device="eth0"}'
values: '9000x29 1500 9000x180'
- series: 'node_network_mtu_bytes{instance="test-model_1234_test-app_test-app/0", device="eth1"}'
values: '1500x240'
alert_rule_test:
- eval_time: 29m
alertname: HostInterfaceMTUSize
exp_alerts: []  # no alert
- eval_time: 30m …
```

Add alert rules for network

---

src/prometheus_alert_rules/pressure.rules

Moving OS-level NRPE checks (CPU related) from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Adding reasonable default Prometheus alert rule in Granada agent charm.
Create alert rules based on [pressure stall information (PSI)](https://www.kernel.org/doc/html/latest/accounting/psi.html)
Tested with `promtool`
```yaml
rule_files:
- pressure.rules
tests:
- interval: 1m
input_series:
- series: 'node_pressure_cpu_waiting_seconds_total{instance="test-instance-1", job="node"}'
values: '0+20x15' # rate = 0.33
- series: 'node_pressure_io_waiting_seconds_total{instance="test-instance-1", job="node"}'
values: '0+20x15' # rate = 0.33
- series: 'node_pressure_memory_waiting_seconds_total{instance="test-instance-1", job="node"}'
values: '0+20x15' # rate …
```

Add Prometheus rules for pressure stall information.

---

src/prometheus_alert_rules/useful.rules

- add alert rule to monitor failed systemd scope units
- add alert rule to monitor number of logged users
These alert rules required to enabled following collectors:
```yaml
enable_collectors:
- logind
- systemd
```
Moving rest NRPE checks from [charm-nrpe](https://git.launchpad.net/charm-nrpe/tree/files/plugins).
Tested with
```yaml
rule_files:
- useful.rules
tests:
- interval: 1m
input_series:
- series: node_systemd_unit_state{instance="test-model_1234_test-app_test-app/0", name="failed-units.scope", state="failed"}
values: '0x5 20 30 40 50 60'
- series: node_systemd_unit_state{instance="test-model_1234_test-app_test-app/0", name="active-units.scope", state="active"}
values: '100x5 80 70 60 50 40'
- series: …
```

Add other useful alert rule based on NRPE

---

src/prometheus_alert_rules/mdadm.rules

* Add alert rules based on mdadm metrics. 
Tested with
```
rule_files:
- ./mdadm.rules
tests:
- interval: 1m
input_series: 
- series: node_md_disks{device="md0", state="active", instance="ubuntu-0"}
values: '1x15'
- series: node_md_disks{device="md1", state="failed", instance="ubuntu-0"}
values: '2x15'
alert_rule_test:
- eval_time: 0m
alertname: RaidDisksFailed
exp_alerts:
- exp_labels:
severity: critical
device: md1
state: failed
instance: ubuntu-0
exp_annotations:
summary: 2 disks failed on device md1.(instance ubuntu-0)
description: >-
Disks failed on raid device md1.
VALUE = 2
LABELS = map[__name__:node_md_disks device:md1 instance:ubuntu-0 state:failed]
- interval: 1m
input_series: 
- series: node_md_disks{device="md0", state="spare", instance="ubuntu-0"} …
```

Add alert rules based on mdadm metrics

---

lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
src/grafana_agent.py
src/k8s_charm.py
src/machine_charm.py
tests/integration/test_charm.py
tests/integration/test_forwards_alerts.py
tests/integration/test_kubectl_delete.py
tests/scenario/test_setup_statuses.py
tests/scenario/test_start_statuses.py
tests/unit/k8s/test_relation_status.py
tests/unit/k8s/test_scrape_configuration.py
tests/unit/machine/test_relation_status.py

This PR fixes #200
https://github.com/canonical/grafana-agent-k8s-operator/issues/200#issuecomment-1576949493
> We could update the ActiveStatus with a message about which ones are disabled, like: `Metrics: off` or `Metrics & Dashboards: off`.
Before this change you need the following three relations (or grafana-dashboards-provider) to be established to get grafana-agent in ActiveStatus:
- grafana-cloud-config
- send-remote-write
- logging-consumer
Run tests ;-)

Grafana agent require only one outgoing relation to be Active

---

lib/charms/grafana_agent/v0/cos_agent.py
requirements.txt
src/k8s_charm.py

Closes #214 
When packing charmcraft will install and update dependencies of charm libraries overriding pins set in the charm's `requirements.txt`. Since there's no version restriction set in `cos-agent` PYDEPS for pydantic, charmcraft will always update and pull the latest version, which will break charms using it. 
Pin pydantic in the cos-agent charm library to less than 2
Charmcraft issue:
https://github.com/canonical/charmcraft/issues/1135
And PR:
https://github.com/canonical/charmcraft/pull/1136
N/A
Pin pydantic's major version in cos-agent PYDEPS

Pin pydantic's major version

---

src/grafana_agent.py

If dashboard titles contain slashes, then the grafana-agent charm fails to handle them properly.
Essentially, the dashboard data is written on a local file, and the dashboard title is used to construct the filename. Any slashes `/` are preserved, therefore would need intermediate dirs to exist. The file write just below will fail, since the directory does not exist.
Replace `/` with `_` (it should not matter)
Came up during https://github.com/canonical/charm-microk8s/pull/88
Properly handle dashboards that contain dashes (`/`) in their title

Do not fail if dashboard titles contain slashes

---

lib/charms/grafana_agent/v0/cos_agent.py

The `refresh_events` field of `COSAgentProvider` are a list of events that should cause a refresh of the `cos-agent` relation data. However, sometimes a wrong relation may be updated instead of the cos-agent relation. Consider the following example:
```yaml
peers:
peer:
interface: peer
provides:
cos-agent:
interface: cos_agent
```
```py
self._cos = COSAgentProvider(
relation_name="cos-agent",
refresh_events=[self.on.peer_relation_changed, self.on.upgrade_charm]
)
```
With the above, we want to update the `cos-agent` relation when a change happens to the peer relation. However, the updated unit data is written on the `peer` relation instead, since `isinstance(event, RelationEvent)` is true and `event.relation` refers to the peer relation.
I could pinpoint the problem by adding relevant log …

Always update the cos-agent relation

---

src/machine_charm.py

The grafana-agent charm will override any existing labels that may be configured in the static_configs
Use `static_config.setdefault("labels", {})`, and then update the dict so that:
- If any `labels` are set in the static config, they are preserved and the juju topology labels are added
- If no `labels` are set in the config, this is equivalent to the previous behavior
Needed for https://github.com/canonical/charm-microk8s/pull/88 (along with a few more PRs I'm making separately)
Supply a static config with existing labels, expect that they are not removed from the resulting scrape jobs.
Respect any labels defined in the metrics endpoints.

Do not override static config labels

---

lib/charms/grafana_agent/v0/cos_agent.py
tests/integration/prometheus-tester/requirements.txt
tests/integration/test_upgrade_charm.py
tox.ini

It may be desired for the metrics endpoints to be generated independently of the lifecycle of the `COSAgentProvider` object. Some use cases are:
- retrieve a bearer token
- retrieve data from other relations, e.g. tokens or certificates
Allow `metrics_endpoints` to be a callable instead of a static list. It will be executed only when the object needs to update the scrape jobs.
Needed for https://github.com/canonical/charm-microk8s/pull/88
Allow a callable to dynamically generate the metrics endpoints

Support a callable for COSAgentProvider.metrics_endpoints

---

lib/charms/grafana_agent/v0/cos_agent.py

Scrape jobs may require more fields, e.g. `authorization` or custom labels for specific targets
If the metrics endpoint passed to `COSAgentProvider` has a `scrape_job` field, then assume that this is a custom job, also added docs (happy to adjust with any recommendation)
Needed for https://github.com/canonical/charm-microk8s/pull/88, also see to #219 
Allow custom scrape jobs in COSAgentProvider

Allow custom scrape jobs in COSAgentProvider

---

requirements.txt
src/grafana_agent.py
src/k8s_charm.py
src/machine_charm.py

Alert rule labels do not match metrics labels.
Apply the principal topology to alert rules defined by grafana-agent.
Fixes #190.
1. Deploy grafana-agent
2. Deploy ubuntu
3. Relate cos -> grafana-agent -> ubuntu
4. Check that the alert rules are labeled as "ubuntu" rather than "grafana-agent"
Fixed an issue where alert rule labels did not match metrics labels.
This is draft at the moment because I need to add tests and investigate whether the same change is needed for logging alerts.

apply principal labels to alert rules defined by grafana-agent

---

.gitignore
lib/charms/grafana_agent/v0/cos_agent.py
requirements.txt
src/grafana_agent.py
src/k8s_charm.py
tests/scenario/test_k8s/conftest.py
tests/scenario/test_k8s/test_dashboard_transfer.py
tests/scenario/test_machine_charm/test_peer_relation.py
tests/scenario/test_machine_charm/test_relation_priority.py
tox.ini

resolves #240 
resolves #87 
currently, dashboards are only forwarded for the machine flavor of grafana agent
forward dashboards for k8s as well
1. deploy cos lite
2. deploy this bundle, with a local build of the charm:
```
bundle: pr-241
saas:
grafana:
url: uk8s:admin/cos.grafana
prometheus:
url: uk8s:admin/cos.prometheus
applications:
ga:
charm: local:grafana-agent-k8s-4
channel: edge
resources:
agent-image: 30
scale: 1
pgsql:
charm: postgresql-k8s
channel: 14/edge
revision: 128
resources:
postgresql-image: 116
scale: 1
relations:
- - ga:metrics-endpoint
- pgsql:metrics-endpoint
- - ga:logging-provider
- pgsql:logging
- - ga:send-remote-write
- prometheus:receive-remote-write
- - ga:grafana-dashboards-provider
- grafana:grafana-dashboard
- - ga:grafana-dashboards-consumer
- …
```

fix(k8s): forward dashboards

---

charmcraft.yaml

K8s charm fails on install hook ([ci ref](https://github.com/canonical/prometheus-k8s-operator/actions/runs/6090925554/job/16526669903?pr=518#step:5:1362)):
```
INFO juju.worker.uniter awaiting error resolution for "install" hook
WARNING unit.grafana-agent/0.install thread '<unnamed>' panicked at 'Python API call failed', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5
WARNING unit.grafana-agent/0.install note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARNING unit.grafana-agent/0.install ModuleNotFoundError: No module named '_cffi_backend'
WARNING unit.grafana-agent/0.install Traceback (most recent call last):
WARNING unit.grafana-agent/0.install   File "./src/charm.py", line 20, in <module>
WARNING …
```

Drop `charm-binary-python-packages` section

---

lib/charms/grafana_agent/v0/cos_agent.py

Fixes #211
Always use insecure_skip_verify for localhost
1. Deploy grafana-agent
2. relate over cos-agent (to zookeeper for example)
3. check that insecure_skip_verify is in /etc/grafana-agent.yaml
Grafana-agent can now scrape TLS endpoints provided over cos-agent.

insecure_skip_verify for localhost

---

lib/charms/operator_libs_linux/v2/snap.py
src/machine_charm.py
tests/scenario/test_machine_charm/test_scrape_configs.py

Update to [latest version (v2) of operator_libs_linux](https://charmhub.io/operator-libs-linux/libraries/snap).
```
charmcraft fetch-lib charms.operator_libs_linux.v2.snap
```
Also update current code that used v1.
This update is not included in #213
Replaces #247
Bumping a major version can be tricky, but the library methods used by the snap are not affected.

Use operator_libs_linux.v2.snap

---

src/prometheus_alert_rules/disk.rules

The metric name `node_filesystem_size_bytes_bytes` appears to be incorrect due to typo. The correct metric name should be `node_filesystem_size_bytes`, and it can be verified from the [source code](https://github.com/prometheus/node_exporter/blob/master/collector/filesystem_common.go#L117) of node exporter.
This is a regression from #186 
Fix the typo: `node_filesystem_size_bytes_bytes` -> `node_filesystem_size_bytes`
Prometheus alert rules
N/A
Fix typo in the Prometheus alert rules for disk

Fix typo in disk.rules

---

charmcraft.yaml

Makes the charm useable on arm64.
Enables packing the charm on arm64.
I am testing Charmed 5G's Control Plane bundle on arm64, requiring the grafana-agent for observability.
Can be tested by packing the charm on an arm64 machine (Raspberry Pi 4/5, Apple M1, etc.). It will require the OCI image to also be built for arm64: https://github.com/canonical/grafana-agent-rock/pull/29
Added arm64 support

feat: Add arm64 support

---

.gitignore
INTEGRATING.md
charmcraft.yaml
lib/charms/loki_k8s/v1/loki_push_api.py
lib/charms/tls_certificates_interface/v2/tls_certificates.py
src/charm.py
src/grafana_agent.py
tests/integration/loki-tester/src/charm.py

This charm overwrites existing topology labels with its own topology labels. This happens because:
1. This charm doesn't have cos-tool, so injection of label matchers is skipped.
2. This charm has an outdated labeling logic: here, all alert labels are being [replaced](https://github.com/canonical/grafana-agent-k8s-operator/blob/5955b98c3ced5f502a03b3ea9948dd4f0f4e1f2a/lib/charms/loki_k8s/v0/loki_push_api.py#L761) by this charm's labels, whereas in cos-lib [only missing labels are added](https://github.com/canonical/cos-lib/blob/486945531c3a95253c2ee3886204071b176e7841/src/cosl/rules.py#L298).
3. This charm has two different use cases for rules that are currently not captured well:
1. Like most charms, this charm has built-in rules and dashboards that need to be enriched with the charm's …

Fix label treatment of related charms

---

src/charm.py
src/grafana_agent.py

Complementary to the fix of https://github.com/canonical/loki-k8s-operator/issues/360
This PR points the `_ca_folder_path` to the correct path to solve the `certificate signed by unknown authority issue` when `gagent` is related over the `certificate_transfer` interface

Fix SSL Cert Issue in Certificate Transfer

---

src/charm.py

Previously, when the relation between grafana-agent and a charm providing a dashboard
(over the grafana-dashboards-consumer relation)
was broken, the dashboards would not be removed.
This fixes that issue, by also running the dashboards changed method when the relation is broken.
- Deploy grafana, grafana-agent-k8s, and a charm that provides a dashboard.
- verify that the dashboards are visible in the grafana web ui
- remove the relation between grafana-agent-k8s and the charm that provides a dashboard
- verify that the dashboards are no longer visible in the grafana web ui.  These dashboards should also be removed from `/var/lib/juju/agents/unit-grafana-agent-0/charm/grafana_dashboards/` in grafana-agent-k8s.

Update dashboards when relation broken

---

lib/charms/observability_libs/v1/cert_handler.py
lib/charms/tempo_k8s/v1/charm_tracing.py
lib/charms/tempo_k8s/v2/tracing.py
src/charm.py
src/grafana_agent.py

Fixes #301
ca cert is pushed into charm container, so pass ca cert path to trace_charm decorator to use that for tls communication with tempo
1- Depends on https://github.com/canonical/tempo-k8s-operator/pull/98
2- Assumes grafana-agent and tempo have tls enabled
3- Assumes CA of grafana-agent is the same for the one used by tempo's cert

charm tracing fails over tls

---

pyproject.toml
tox.ini

codespell 2.3 introduces changes that raises "assertIn" as a spelling mistake. 
Add "assertIn" to codespell's dictionary and unpin codespell
CI coverage handles this.  If it passes linting, it works.

Add codespell dictionary settings to pyproject.toml

---

metadata.yaml
tox.ini

Contributes to #296.  That issue is affected by a [hard to reproduce upstream bug](https://github.com/prometheus/prometheus/issues/11589) that may have been fixed in 0.36.  
Bumps the grafana-agent container image
grafana-agent may include breaking changes in minor version bumps.  I've scanned through the release notes between 0.35 (current version) and 0.40.5 (latest), but I don't have enough background context to really catch anything that affects us.  When reviewing, please also read through this summary of breaking changes and highlight anything that matters:
* [v0.40.5](https://github.com/grafana/agent/releases/tag/v0.40.5)
* some `pg_stat_*` metrics were changed because `prometheus.exporter.postgres` was updated.  
* [v0.40.0](https://github.com/grafana/agent/releases/tag/v0.40.0)
* …

bump grafana-agent container image to 0.40.4-22.04_stable

---

tests/integration/conftest.py
tox.ini

Retry packing the charm due to an intermittent issue where c`harmcraft` fails to build the charm for an unknown reason.

Fix integration tests

---

lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
tox.ini

This PR updates the `cloud_config_requirer` lib to its last version, so [we can fix this same issue](https://github.com/canonical/grafana-agent-operator/issues/203), but in the k8s operator
> We are not updating the others libs in this PR, since we are addressing it in a separate PR because [it needs modification to charm code](https://github.com/canonical/grafana-agent-k8s-operator/issues/328).
Pack the charm, and deploy this bundle:
```yaml
bundle: kubernetes
applications:
agent:
charm: local:grafana-agent-k8s-0
scale: 1
constraints: arch=amd64
storage:
data: kubernetes,1,1024M
trust: true
flog:
charm: flog-k8s
channel: latest/edge
revision: 8
base: ubuntu@20.04/stable
resources:
workload-image: 2
scale: 1
constraints: arch=amd64
gci:
charm: grafana-cloud-integrator
channel: latest/edge …
```

update cloud_config_requirer lib

---

lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
src/grafana_agent.py

This PR partially is in tandem with the PR https://github.com/canonical/grafana-cloud-integrator/pull/21 and should be merged after.
It also fixes (partially) https://github.com/canonical/grafana-cloud-integrator/issues/18 (I'm also opening a PR in the machine charm).
⚠️ Do NOT merge before the other one, it contains the (yet) unreleased version of the `cloud_config_requirer` library.
**grafana-cloud-integrator#21** (the PR for the CA issue) is addressed by saving the CA coming from relation data to file, and then calling `update-ca-certificates` as usual. We do this on the custom `cloud-config-available` event, which is emitted whenever there is a relation joined/changed/broken involving the cloud-integrator relation.
**grafana-cloud-integrator#18** (the config issue) is solved by …

feat: support external ca from cloud-integrator

---

src/grafana_dashboards/node-exporter-full.json

There is a dashboard title collision with the one in the grafana-agent machine charm.
Rename the title as suggested in https://github.com/canonical/observability/pull/206/files#r1863947198
uid collision will be addressed later as indicated in https://github.com/canonical/observability/pull/206.

Rename the title of the node-exporter dashboard

---

src/grafana_agent.py
tests/scenario/test_tracing_integration.py

When a tracing backend isn't connected, grafana-agent errors out due to a missing guard. Also, when the guard is added, the same issue as in https://github.com/canonical/grafana-agent-operator/issues/219 appears.
Add the same guard as in the machine charm. Also return an empty receivers list if the upstream tracing backend isn't ready yet.
Deploy the following bundle:
```
bundle: kubernetes
applications:
grafana-agent-k8s:
charm: local:grafana-agent-k8s-2
scale: 1
constraints: arch=amd64
storage:
data: kubernetes,1,1024M
postgresql-k8s:
charm: postgresql-k8s
channel: 14/edge
revision: 470
resources:
postgresql-image: 164
scale: 1
constraints: arch=amd64
storage:
pgdata: kubernetes,1,1024M
trust: true
relations:
- - postgresql-k8s:tracing
- grafana-agent-k8s:tracing-provider
```
Observe …

Return empty receivers list if tracing backend isn't connected

---

requirements.txt
src/charm.py
tests/scenario/test_dashboard_transfer.py

Charm code use deprecated class from cos-lib.
Refactor to use LZMABase64 instead of the deprecated GrafanaDashboard.
In tandem with:
- https://github.com/canonical/cos-lib/pull/114
- https://github.com/canonical/grafana-k8s-operator/pull/363
- https://github.com/canonical/grafana-agent-operator/pull/224

Replace GrafanaDashboard with LZMABase64
