tox.ini

FIX #3 - Unit tests

---

lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
requirements.txt
src/charm.py
src/prometheus_alert_rules/grafana_agent_unavailable.rule
tests/unit/test_charm.py

This PR depends on https://github.com/canonical/prometheus-operator/pull/147 being shipped to at least `edge`

Add support for remote write towards prometheus-k8s charm

---

lib/charms/loki_k8s/v0/log_proxy.py
lib/charms/loki_k8s/v0/loki_push_api.py
metadata.yaml
src/charm.py
tests/unit/test_charm.py

This PR updates:
- Loki libraries
- Grafana agent image

Update libs and grafana agent image

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py

This PR updates the Prometheus scrape charm libraries to latest published versions.

Updated Prometheus scrape charm library

---

.github/workflows/promote.yaml
.github/workflows/pull-request.yaml
tox.ini

Github action to promote a release to a different channel. Testing it out here before copying over to other repos.

promote charm action

---

.github/workflows/promote.yaml

Typo and change the default channel.

Fix promote action.

---

.github/workflows/promote.yaml
tests/integration/test_charm.py

Fixes to the action that I did in today's meeting.

Make input more clear, fix secret name, and run with stable charmcraft

---

.github/workflows/release-edge.yaml

This PR attempts to fix the "release to edge" CI. I'm not really sure how to test it other than just merging and seeing what happens.

fix release CI

---

CONTRIBUTING.md
README.md
k8s_metadata.yaml
metadata.yaml

Move to the `grafana-agent` ROCK image on GHCR

Use a ROCK image

---

k8s_metadata.yaml
machine_metadata.yaml
src/machine_charm.py

- Charm currently installs a development snap.
- Charm does not contain the machine subordinate relation.
- Add relation
- Replace the snap used
- Add some more granular statuses
Fix metadata and snap usage

Fix metadata and snap usage

---

src/machine_charm.py

Make the static configs into a list so it parses

Fix indentation

---

src/grafana_dashboards/node-exporter-full.json

Just some spelling corrections.

spelling errors

---

src/grafana_agent.py
src/machine_charm.py

```
unit-agent-5: 16:14:00.711 DEBUG unit.agent/5.juju-log send-remote-write:26: Emitting custom event <PrometheusRemoteWriteEndpointsChangedEvent via GrafanaAgentMachineCharm/PrometheusRemoteWriteConsumer[send-remote-write]/on/endpoints_changed[26]>.
unit-agent-5: 16:14:00.717 ERROR unit.agent/5.juju-log send-remote-write:26: Uncaught exception while in charm code:
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-agent-5/charm/./src/charm.py", line 259, in <module>
main(GrafanaAgentMachineCharm)
File "/var/lib/juju/agents/unit-agent-5/charm/venv/ops/main.py", line 436, in main
_emit_charm_event(charm, dispatcher.event_name)
File "/var/lib/juju/agents/unit-agent-5/charm/venv/ops/main.py", line 144, in _emit_charm_event
event_to_emit.emit(*args, **kwargs)
File …
```

Type fixes

---

src/grafana_agent.py
src/machine_charm.py
tests/unit/k8s/test_update_status.py
tests/unit/machine/test_update_status.py

charm to use cos-machine over juju-info when available

Sub relation priority

---

lib/charms/grafana_agent/v0/cos_machine.py
src/machine_charm.py
tests/integration/prometheus.py
tests/integration/test_forwards_alerts.py
tests/scenario/machine_charm/test_setup_statuses.py
tests/unit/k8s/test_scrape_configuration.py
tests/unit/k8s/test_update_status.py
tests/unit/machine/test_update_status.py

Can't `json.loads({})`. Make the default return into `"{}"` instead, so it'll load correctly/empty

Fix a possible JSON loading exception

---

src/grafana_agent.py
src/machine_charm.py
tests/integration/prometheus.py

Fix labels

---

lib/charms/grafana_agent/v0/cos_machine.py
requirements.txt
src/loki_alert_rules/high_error_rate.rule
src/prometheus_alert_rules/high_cpu_iowait.rule
src/prometheus_alert_rules/memory_pressure.rule
src/prometheus_alert_rules/oomkill.rule
tests/integration/prometheus.py

Swap to COSL instead of re-using the Prom/Loki AlertRules to minimize deps for end-users and side effects

Use cosl for Rules and JujuTopology

---

lib/charms/grafana_agent/v0/cos_machine.py
requirements.txt

Top level documentation for cos_machine lib

top level documentation for cos_machine lib 

---

k8s_metadata.yaml
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/observability_libs/v0/juju_topology.py
lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
tests/integration/helpers.py
tests/integration/test_kubectl_delete.py
tests/integration/test_upgrade_charm.py
tests/unit/test_alerts.py
tox.ini

Fetch all libs, pull in the uk8s_group helper, xfail likely failures (like trying to upgrade from CH when the version in CH will have failing patches ATM)

Reconcile CI

---

machine_metadata.yaml

This PR fixes a wrong scope for a cross model relation.
See: https://chat.charmhub.io/charmhub/pl/joqi1qz6qpy9mxjkdxxme95dah

wrong scope for grafana-dashboards-provider relation

---

lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/observability_libs/v0/juju_topology.py
lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/machine_charm.py
tests/unit/machine/test_fstab_parsing.py

If there's only one matching entry with an owning snap in fstab, use that without checking the source at all.
If there's more than one, coalesce the relative path and the provided endpoint name into sets of unique characters, then find the one with the longest intersection as the most likely candidate.
Add a couple more assertions in the existing unit test to verify this.

Be looser with finding snap plug mounts

---

src/grafana_agent.py
tests/scenario/test_machine_charm/test_cos_agent_e2e.py
tests/unit/machine/test_relation_status.py

This PR fix #164.
The solution is a workaround until [this issue in ops](https://github.com/canonical/operator/issues/888) is fixed

Set BlockedStatus when one mandatory relation is removed

---

lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/observability_libs/v0/cert_handler.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
lib/charms/tls_certificates_interface/v2/tls_certificates.py
src/grafana_agent.py
tests/scenario/test_machine_charm/test_peer_relation.py
tests/unit/k8s/test_alerts.py
tests/unit/k8s/test_scrape_configuration.py

This updates all charm libs. Partially helps with #190
Update the libs and resolve any issues.
Behavior should not change so just test that the charm seems to work.
Update charm libraries.

update charm libs

---

src/machine_charm.py

The topology labels are wrong for alerts received over cos-agent.
Partially solves #190
Overwrite the topology labels.
1. Relate zookeeper, grafana-agent, and hardware-observer all to each other.
2. Relate grafana-agent to cos.
3. Check that alert rule expression all use zookeeper topology.
Fixed and issue where the alert rules forwarded over cos-agent had the wrong labels.

overwrite the topology labels when recieving alerts over cos-agent

---

tests/scenario/test_machine_charm/test_alert_labels.py

We don't have a test for this yet. Partially completes #190
Add the test
Not needed as this is itself a test.
-

test to ensure alert rules are labeled correctly

---

metadata.yaml

change upstream-source

---

src/grafana_agent.py

This change is mainly necessary for the charm static analysis to pass, making sure we don't break CI :)

use the generic cloud integrator charm

---

requirements.txt
src/grafana_agent.py
tests/scenario/test_setup_statuses.py
tests/unit/test_relation_status.py
tests/unit/test_scrape_configuration.py

Mandatory relation pairs were modeled incorrectly.
Use helper for mandatory relation pairs.
In tandem with:
- https://github.com/canonical/cos-lib/pull/25
- https://github.com/canonical/grafana-agent-operator/pull/85

Use helper for mandatory relation pairs

---

charmcraft.yaml
lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/observability_libs/v1/cert_handler.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
lib/charms/tempo_coordinator_k8s/v0/tracing.py
lib/charms/tls_certificates_interface/v3/tls_certificates.py
tests/unit/conftest.py
tests/unit/test_alerts.py
tests/unit/test_scrape_configuration.py
tox.ini

Mirroring https://github.com/canonical/grafana-agent-operator/pull/231.

Update charmcraft.yaml: chmod 775 cos-tool

---

.github/workflows/release.yaml
charmcraft.yaml
pyproject.toml

prepare for track 2

---

README.md

chore: add deprecation notice for grafana agent k8s

---

lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
src/grafana_agent.py

feat: upgrade to certificate-transfer v1 library

---

lib/charms/loki_k8s/v1/loki_push_api.py
src/grafana_agent.py
tests/unit/test_alert_labels.py

Relates to https://github.com/canonical/loki-k8s-operator/pull/530
Mimics https://github.com/canonical/grafana-agent-k8s-operator/pull/395

feat: add extra_alert_labels functionality to log alerts
